[package]
name = "cartridge-identity"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cartridge-core = { path = "../cartridge-core" }
ed25519-dalek.workspace = true
fs4 = "1.1.0"
hex.workspace = true
rand.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
