[package]
name = "cartridge-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "cartridge"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
cartridge-core = { path = "../cartridge-core" }
cartridge-desktop = { path = "../cartridge-desktop" }
cartridge-dev = { path = "../cartridge-dev" }
cartridge-identity = { path = "../cartridge-identity" }
cartridge-network = { path = "../cartridge-network" }
cartridge-release = { path = "../cartridge-release" }
cartridge-runtime = { path = "../cartridge-runtime" }
cartridge-trace = { path = "../cartridge-trace" }
clap.workspace = true
hex.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[dev-dependencies]
tempfile = "3.27.0"

[lints]
workspace = true
